# bot/texts/en.py
TEXTS = {
    "welcome": "👋 <b>Welcome to AI Personal Trainer!</b>\n\nI'll be your personal trainer — no gym needed. Let's start!",
    "calibration_start": "📋 <b>Initial Setup</b>\n\nLet me ask you a few questions to create a personalized program.",
    "choose_language": "🌍 Choose language / Выберите язык:",
    "menu_workout": "🏋️ Workout",
    "menu_progress": "📊 Progress",
    "menu_achievements": "🏆 Achievements",
    "menu_calibration": "📋 Calibration",
    "menu_schedule": "📅 Schedule",
    "menu_challenge": "🎯 30-day Challenge",
    "menu_equipment": "🎒 Equipment",
    "menu_settings": "⚙️ Settings",
    "menu_admin": "🔧 Admin",
    "settings_title": "⚙️ <b>Settings</b>\n\nChoose an action:",
    "settings_language": "🌍 Change language",
    "settings_export": "📤 Export data",
    "settings_reset": "🗑️ Reset progress",
    "settings_main_menu": "◀️ Main menu",
    "language_changed": "✅ Language changed: <b>{language}</b>",
    "language_choose": "🌍 Choose language / Выберите язык:",
    "main_menu_title": "⚡ <b>GYM Control Center</b>\n\nYour training system modules are here: workout start, progress, achievements, schedule, challenges, inventory, and settings.\n\nChoose a module below and I will open the next screen.",
    "workout_start": "🏋️ <b>Starting workout!</b>\n\nHow are you feeling today?",
    "rest_timer": "⏱ Rest <b>{seconds} sec</b>\n\nPress when ready.",
    "rest_done": "🔔 <b>Rest complete!</b> Time for next set 💪",
    "workout_complete": "🏁 <b>Workout complete!</b>",
    "deload_notice": "📉 <b>Deload</b> {exercise}: {old}→{new} kg (no progress {n} sessions)",
    "deload_after_break": "💪 Welcome back! You were away {days} days, weights adjusted to ease back in.",
    "challenge_30_joined": "🎯 You joined the <b>30-day challenge!</b> Day 1 starts now.",
    "challenge_30_progress": "🎯 <b>30-day challenge</b>\n\n{bar}\nDay {current}/30 — keep going!",
    "challenge_30_complete": "🏆 <b>You completed the 30-day challenge!</b> Incredible!",
    "admin_panel": "🔧 <b>Admin Panel</b>\n\n👥 Users: <b>{users}</b>\n🏋️ Workouts: <b>{sessions}</b>\n📈 Active 7d: <b>{active}</b>",
}
