"""Exercises seed data — part 2: Shoulders, Arms, Legs, Core, Cardio"""
EXERCISES_REST = [
    # SHOULDERS
    {"code": "overhead_press", "name_ru": "Жим штанги стоя", "name_en": "Overhead Press",
     "muscle": "front_delts", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 4,
     "met": 6.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Overhead_Shoulder_Press/Smith_Machine_Overhead_Shoulder_Press.gif",
     "instructions": ["Хват чуть шире плеч", "Жми строго вверх", "Вынеси голову вперёд в верхней точке"],
     "tips": ["Напряги пресс и ягодицы"], "mistakes": ["Прогиб поясницы"]},
    {"code": "db_shoulder_press", "name_ru": "Жим гантелей сидя", "name_en": "DB Shoulder Press",
     "muscle": "front_delts", "equipment": "dumbbell", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 5.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/Dumbbell_Shoulder_Press.gif",
     "instructions": ["Гантели у плеч", "Жми строго вверх", "Не блокируй локти"],
     "tips": ["Спина ровная"], "mistakes": ["Раскачка корпуса"]},
    {"code": "lateral_raises", "name_ru": "Махи гантелями в стороны", "name_en": "Lateral Raises",
     "muscle": "side_delts", "equipment": "dumbbell", "eq_cat": "portable", "type": "isolation", "difficulty": 1,
     "met": 3.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/Dumbbell_Shoulder_Press.gif",
     "instructions": ["Стой прямо", "Поднимай до параллели полу", "Медленно опускай"],
     "tips": ["Большой палец чуть вниз"], "mistakes": ["Рывки трапецией"]},
    {"code": "arnold_press", "name_ru": "Жим Арнольда", "name_en": "Arnold Press",
     "muscle": "front_delts", "equipment": "dumbbell", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 5.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Arnold_Press/Kettlebell_Arnold_Press.gif",
     "instructions": ["Гантели перед лицом ладонями к себе", "Вращай и жми вверх", "Обратно"],
     "tips": ["Все три пучка дельт"], "mistakes": ["Слишком быстро"]},
    # BICEPS
    {"code": "barbell_curl", "name_ru": "Подъём штанги на бицепс", "name_en": "Barbell Curl",
     "muscle": "biceps", "equipment": "barbell", "eq_cat": "portable", "type": "isolation", "difficulty": 2,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/Barbell_Curl.gif",
     "instructions": ["Хват снизу на ширине плеч", "Сгибай только в локте", "Медленно вниз"],
     "tips": ["Локти прижаты к корпусу"], "mistakes": ["Помощь корпусом"]},
    {"code": "db_curl", "name_ru": "Сгибание с гантелями", "name_en": "Dumbbell Curl",
     "muscle": "biceps", "equipment": "dumbbell", "eq_cat": "portable", "type": "isolation", "difficulty": 1,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Incline_Dumbbell_Curl/Alternate_Incline_Dumbbell_Curl.gif",
     "instructions": ["Попеременно или вместе", "Разворачивай ладонь наружу", "Полная амплитуда"],
     "tips": ["Супинация в верхней точке"], "mistakes": ["Отведение локтя"]},
    {"code": "hammer_curl", "name_ru": "Молотки", "name_en": "Hammer Curl",
     "muscle": "biceps", "equipment": "dumbbell", "eq_cat": "portable", "type": "isolation", "difficulty": 1,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/Alternate_Hammer_Curl.gif",
     "instructions": ["Нейтральный хват", "Сгибай строго в локте"],
     "tips": ["Хорошо для брахиалиса"], "mistakes": ["Раскачка"]},
    # TRICEPS
    {"code": "tricep_dips", "name_ru": "Отжимания на брусьях", "name_en": "Dips",
     "muscle": "triceps", "equipment": "dip_bar", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 6.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/Bench_Dips.gif",
     "instructions": ["Хват на брусьях", "Наклон вперёд для груди, прямо для трицепса", "Опускайся ниже локтя"],
     "tips": ["Полная амплитуда"], "mistakes": ["Слишком широкие брусья"]},
    {"code": "close_grip_bench", "name_ru": "Жим узким хватом", "name_en": "Close-Grip Bench Press",
     "muscle": "triceps", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 5.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Close-Grip_Bench_Press/Smith_Machine_Close-Grip_Bench_Press.gif",
     "instructions": ["Хват на ширине плеч", "Локти вдоль тела", "Жим вверх"],
     "tips": ["Не узкий хват — травма запястий"], "mistakes": ["Локти в стороны"]},
    {"code": "tricep_pushdown", "name_ru": "Разгибание на блоке", "name_en": "Tricep Pushdown",
     "muscle": "triceps", "equipment": "cable", "eq_cat": "stationary", "type": "isolation", "difficulty": 1,
     "met": 3.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Grip_Triceps_Pushdown/Reverse_Grip_Triceps_Pushdown.gif",
     "instructions": ["Верхний блок", "Локти прижаты", "Разгибай до прямой"],
     "tips": ["Наклон чуть вперёд"], "mistakes": ["Локти уходят вперёд"]},
    {"code": "overhead_tricep_ext", "name_ru": "Французский жим", "name_en": "Overhead Tricep Extension",
     "muscle": "triceps", "equipment": "dumbbell", "eq_cat": "portable", "type": "isolation", "difficulty": 2,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/Cable_Rope_Overhead_Triceps_Extension.gif",
     "instructions": ["Стоя или сидя", "Гантель за голову", "Разгибай медленно"],
     "tips": ["Длинная головка трицепса"], "mistakes": ["Разведение локтей"]},
    # QUADS
    {"code": "squat", "name_ru": "Приседания со штангой", "name_en": "Barbell Squat",
     "muscle": "quadriceps", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 4,
     "met": 6.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/Barbell_Squat.gif",
     "instructions": ["Штанга на трапеции", "Ноги чуть шире плеч", "Присед ниже параллели"],
     "tips": ["Колени по носкам", "Смотри прямо"], "mistakes": ["Колени внутрь", "Отрыв пяток"]},
    {"code": "goblet_squat", "name_ru": "Приседание с гирей", "name_en": "Goblet Squat",
     "muscle": "quadriceps", "equipment": "kettlebell", "eq_cat": "portable", "type": "compound", "difficulty": 1,
     "met": 5.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/Goblet_Squat.gif",
     "instructions": ["Держи снаряд у груди", "Присед глубокий", "Колени наружу"],
     "tips": ["Отлично для техники"], "mistakes": ["Опускание снаряда вниз"]},
    {"code": "bodyweight_squat", "name_ru": "Приседания без веса", "name_en": "Bodyweight Squat",
     "muscle": "quadriceps", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 1,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/Bodyweight_Squat.gif",
     "instructions": ["Ноги на ширине плеч", "Руки вперёд для баланса", "Ниже параллели"],
     "tips": ["Пятки на полу"], "mistakes": ["Колени внутрь"]},
    {"code": "leg_press_ex", "name_ru": "Жим ног", "name_en": "Leg Press",
     "muscle": "quadriceps", "equipment": "machine", "eq_cat": "stationary", "type": "compound", "difficulty": 1,
     "met": 5.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/Leg_Press.gif",
     "instructions": ["Спина к спинке", "Ноги на середине платформы", "Не выпрямляй до конца"],
     "tips": ["Широкая постановка = больше ягодиц"], "mistakes": ["Отрыв поясницы"]},
    {"code": "lunge", "name_ru": "Выпады", "name_en": "Lunges",
     "muscle": "quadriceps", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 2,
     "met": 5.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/Dumbbell_Lunges.gif",
     "instructions": ["Шаг вперёд", "Колено опускай вниз", "Вернись и смени ногу"],
     "tips": ["Торс прямой"], "mistakes": ["Колено уходит внутрь"]},
    {"code": "bulgarian_split", "name_ru": "Болгарские выпады", "name_en": "Bulgarian Split Squat",
     "muscle": "quadriceps", "equipment": "dumbbell", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 6.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/3_4_Sit-Up/3_4_Sit-Up.gif",
     "instructions": ["Одна нога сзади на скамье", "Присед до параллели", "Держи корпус прямо"],
     "tips": ["Отлично для ягодиц и баланса"], "mistakes": ["Колено переднего касается пола"]},
    # HAMSTRINGS
    {"code": "rdl", "name_ru": "Румынская тяга", "name_en": "Romanian Deadlift",
     "muscle": "hamstrings", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 6.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/Romanian_Deadlift.gif",
     "instructions": ["Штанга у бёдер", "Наклон с прямой спиной", "До натяжения бицепса бедра"],
     "tips": ["Отводи таз назад"], "mistakes": ["Округление поясницы"]},
    {"code": "leg_curl_ex", "name_ru": "Сгибание ног лёжа", "name_en": "Lying Leg Curl",
     "muscle": "hamstrings", "equipment": "machine", "eq_cat": "stationary", "type": "isolation", "difficulty": 1,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/Lying_Leg_Curls.gif",
     "instructions": ["Лёжа лицом вниз", "Сгибай до максимума", "Медленно вниз"],
     "tips": ["Пиковое сокращение"], "mistakes": ["Отрыв таза"]},
    # GLUTES
    {"code": "hip_thrust", "name_ru": "Ягодичный мостик со штангой", "name_en": "Hip Thrust",
     "muscle": "glutes", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 5.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/Barbell_Hip_Thrust.gif",
     "instructions": ["Плечи на скамье", "Штанга на поясе", "Поднимай таз до прямой линии"],
     "tips": ["Сожми ягодицы вверху"], "mistakes": ["Переразгибание поясницы"]},
    {"code": "glute_bridge", "name_ru": "Ягодичный мостик", "name_en": "Glute Bridge",
     "muscle": "glutes", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 1,
     "met": 4.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/Barbell_Glute_Bridge.gif",
     "instructions": ["Лёжа, стопы у ягодиц", "Поднимай таз", "Сожми ягодицы"],
     "tips": ["Одноногий вариант сложнее"], "mistakes": ["Прогиб поясницы"]},
    # CALVES
    {"code": "standing_calf_raise", "name_ru": "Подъём на носки стоя", "name_en": "Standing Calf Raise",
     "muscle": "calves", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 1,
     "met": 3.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocking_Standing_Calf_Raise/Rocking_Standing_Calf_Raise.gif",
     "instructions": ["Встань на край ступени", "Подъём на носки", "Медленно вниз"],
     "tips": ["Растяги внизу"], "mistakes": ["Слишком быстрые повторы"]},
    # CORE
    {"code": "plank", "name_ru": "Планка", "name_en": "Plank",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 1,
     "met": 3.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/Plank.gif",
     "instructions": ["Упор на предплечья", "Тело — прямая линия", "Держи 30-60 сек"],
     "tips": ["Напряги пресс и ягодицы"], "mistakes": ["Таз вверх или вниз"]},
    {"code": "crunches", "name_ru": "Скручивания", "name_en": "Crunches",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 1,
     "met": 3.5, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunches/Crunches.gif",
     "instructions": ["Лёжа, руки за голову", "Поднимай плечи", "Медленно вниз"],
     "tips": ["Не тяни за шею"], "mistakes": ["Рывки шеей"]},
    {"code": "leg_raises", "name_ru": "Подъём ног лёжа", "name_en": "Lying Leg Raises",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 2,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/3_4_Sit-Up/3_4_Sit-Up.gif",
     "instructions": ["Лёжа, руки под ягодицы", "Поднимай прямые ноги до 90°", "Медленно вниз"],
     "tips": ["Нижний пресс"], "mistakes": ["Прогиб поясницы"]},
    {"code": "hanging_leg_raises", "name_ru": "Подъём ног в висе", "name_en": "Hanging Leg Raises",
     "muscle": "abs", "equipment": "pullup_bar", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 5.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/Hanging_Leg_Raise.gif",
     "instructions": ["Вис на перекладине", "Поднимай ноги до 90°", "Медленно вниз"],
     "tips": ["Не раскачивайся"], "mistakes": ["Рывки корпусом"]},
    {"code": "russian_twist", "name_ru": "Русский твист", "name_en": "Russian Twist",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 2,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/Russian_Twist.gif",
     "instructions": ["Сидя с наклоном 45°", "Поворачивай корпус", "С весом сложнее"],
     "tips": ["Дыши равномерно"], "mistakes": ["Слишком быстро"]},
    {"code": "ab_wheel", "name_ru": "Ролик для пресса", "name_en": "Ab Wheel Rollout",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 4,
     "met": 5.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/3_4_Sit-Up/3_4_Sit-Up.gif",
     "instructions": ["Стоя на коленях", "Катись вперёд прямыми руками", "Напрягай пресс"],
     "tips": ["Одно из лучших для кора"], "mistakes": ["Прогиб поясницы"]},
    # TRAPS
    {"code": "barbell_shrugs", "name_ru": "Шраги со штангой", "name_en": "Barbell Shrugs",
     "muscle": "traps", "equipment": "barbell", "eq_cat": "portable", "type": "isolation", "difficulty": 1,
     "met": 4.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shrug/Barbell_Shrug.gif",
     "instructions": ["Штанга в опущенных руках", "Поднимай плечи к ушам", "Задержи на секунду"],
     "tips": ["Не крути плечами"], "mistakes": ["Сгибание локтей"]},
    # CARDIO
    {"code": "burpees", "name_ru": "Бёрпи", "name_en": "Burpees",
     "muscle": "full_body", "equipment": None, "eq_cat": "none", "type": "cardio", "difficulty": 3,
     "met": 8.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/3_4_Sit-Up/3_4_Sit-Up.gif",
     "instructions": ["Присед → упор лёжа → отжимание → прыжок вверх"],
     "tips": ["Отличный кардио-элемент"], "mistakes": ["Горб в упоре лёжа"]},
    {"code": "mountain_climbers", "name_ru": "Альпинист", "name_en": "Mountain Climbers",
     "muscle": "abs", "equipment": None, "eq_cat": "none", "type": "cardio", "difficulty": 2,
     "met": 7.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/Mountain_Climbers.gif",
     "instructions": ["Упор лёжа", "Попеременно тяни колени к груди", "Быстро"],
     "tips": ["Высокий темп = кардио"], "mistakes": ["Таз высоко"]},
    {"code": "jumping_jacks", "name_ru": "Прыжки с разведением рук", "name_en": "Jumping Jacks",
     "muscle": "full_body", "equipment": None, "eq_cat": "none", "type": "cardio", "difficulty": 1,
     "met": 7.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/3_4_Sit-Up/3_4_Sit-Up.gif",
     "instructions": ["Прыжок с разведением ног и рук", "Обратно"],
     "tips": ["Хорошая разминка"], "mistakes": []},
    {"code": "jump_rope_ex", "name_ru": "Прыжки со скакалкой", "name_en": "Jump Rope",
     "muscle": "calves", "equipment": "jump_rope", "eq_cat": "portable", "type": "cardio", "difficulty": 2,
     "met": 10.0, "gif_url": "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Jumping/Rope_Jumping.gif",
     "instructions": ["Небольшие прыжки на носках", "Запястья вращают"],
     "tips": ["Лучший кардио-инструмент"], "mistakes": ["Прыжки слишком высоко"]},
]
