"""Exercises seed data — part 1: Chest, Back"""
EXERCISES_CHEST_BACK = [
    {"code": "pushup", "name_ru": "Отжимания от пола", "name_en": "Push-up",
     "muscle": "chest", "equipment": None, "eq_cat": "none", "type": "compound", "difficulty": 1,
     "met": 4.0, "photo": "https://via.placeholder.com/400x300?text=Push-up",
     "instructions": ["Упор лёжа — плечи над запястьями", "Опускайся до касания грудью пола", "Выжмись вверх"],
     "tips": ["Держи корпус прямым", "Не провисай в пояснице"], "mistakes": ["Провисание таза"]},
    {"code": "wide_pushup", "name_ru": "Широкие отжимания", "name_en": "Wide Push-up",
     "muscle": "chest", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 1,
     "met": 4.0, "photo": "https://via.placeholder.com/400x300?text=Wide-Push-up",
     "instructions": ["Руки шире плеч", "Опускайся медленно 3 сек", "Жми вверх"],
     "tips": ["Акцент на внешнюю грудь"], "mistakes": ["Потеря напряжения вверху"]},
    {"code": "diamond_pushup", "name_ru": "Отжимания алмаз", "name_en": "Diamond Push-up",
     "muscle": "chest", "equipment": None, "eq_cat": "none", "type": "isolation", "difficulty": 2,
     "met": 4.5, "photo": "https://via.placeholder.com/400x300?text=Diamond-Push-up",
     "instructions": ["Руки вместе под грудью", "Локти двигаются вдоль тела"],
     "tips": ["Трицепс + внутренняя грудь"], "mistakes": ["Разведение локтей"]},
    {"code": "bench_press", "name_ru": "Жим штанги лёжа", "name_en": "Barbell Bench Press",
     "muscle": "chest", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 6.0, "photo": "https://via.placeholder.com/400x300?text=Bench-Press",
     "instructions": ["Хват чуть шире плеч", "Опусти штангу к нижней части груди", "Выжми вверх"],
     "tips": ["Своди лопатки", "Стопы на полу"], "mistakes": ["Отрыв таза", "Слишком широкий хват"]},
    {"code": "incline_bench_press", "name_ru": "Жим на наклонной скамье", "name_en": "Incline Bench Press",
     "muscle": "chest", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 6.0, "photo": "https://via.placeholder.com/400x300?text=Incline-Bench",
     "instructions": ["Угол скамьи 30-45°", "Опусти штангу к верхней части груди", "Выжми вверх"],
     "tips": ["Акцент верхняя грудь"], "mistakes": ["Слишком крутой угол"]},
    {"code": "db_bench_press", "name_ru": "Жим гантелей лёжа", "name_en": "Dumbbell Bench Press",
     "muscle": "chest", "equipment": "dumbbells", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 5.5, "photo": "https://via.placeholder.com/400x300?text=DB-Bench",
     "instructions": ["Гантели у плеч", "Жим вверх с поворотом", "Сведи руки вверху"],
     "tips": ["Больше амплитуда чем со штангой"], "mistakes": ["Слишком тяжёлые гантели"]},
    {"code": "db_flyes", "name_ru": "Разводка гантелей", "name_en": "Dumbbell Flyes",
     "muscle": "chest", "equipment": "dumbbells", "eq_cat": "portable", "type": "isolation", "difficulty": 2,
     "met": 4.5, "photo": "https://via.placeholder.com/400x300?text=DB-Flyes",
     "instructions": ["Лёжа, гантели над грудью", "Разводи дугой вниз", "Своди обратно"],
     "tips": ["Лёгкий сгиб локтей"], "mistakes": ["Полное выпрямление локтей"]},
    {"code": "cable_crossover", "name_ru": "Кроссовер в блоке", "name_en": "Cable Crossover",
     "muscle": "chest", "equipment": "cable_machine", "eq_cat": "stationary", "type": "isolation", "difficulty": 1,
     "met": 4.0, "photo": "https://via.placeholder.com/400x300?text=Cable-Crossover",
     "instructions": ["Блоки на уровне плеч", "Своди руки перед собой", "Держи напряжение"],
     "tips": ["Наклон вперёд для изоляции"], "mistakes": ["Рывки плечом"]},
    {"code": "pull_up", "name_ru": "Подтягивания", "name_en": "Pull-up",
     "muscle": "back", "equipment": "pull_up_bar", "eq_cat": "portable", "type": "compound", "difficulty": 3,
     "met": 8.0, "photo": "https://via.placeholder.com/400x300?text=Pull-up",
     "instructions": ["Хват сверху шире плеч", "Тяни грудь к перекладине", "Медленно опускайся"],
     "tips": ["Не раскачивайся", "Лопатки вниз-назад"], "mistakes": ["Полуподтягивания", "Раскачка"]},
    {"code": "chin_up", "name_ru": "Подтягивания обратным хватом", "name_en": "Chin-up",
     "muscle": "back", "equipment": "pull_up_bar", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 8.0, "photo": "https://via.placeholder.com/400x300?text=Chin-up",
     "instructions": ["Хват снизу чуть уже плеч", "Тяни к подбородку", "Медленно вниз"],
     "tips": ["Больше бицепса"], "mistakes": ["Слишком широкий хват"]},
    {"code": "barbell_row", "name_ru": "Тяга штанги в наклоне", "name_en": "Bent-over Barbell Row",
     "muscle": "back", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 4,
     "met": 6.0, "photo": "https://via.placeholder.com/400x300?text=Barbell-Row",
     "instructions": ["Наклон 45°, спина прямая", "Тяни к пупку", "Локти вдоль тела"],
     "tips": ["Своди лопатки в верхней точке"], "mistakes": ["Круглая спина", "Рывки"]},
    {"code": "db_row", "name_ru": "Тяга гантели в наклоне", "name_en": "Dumbbell Row",
     "muscle": "back", "equipment": "dumbbells", "eq_cat": "portable", "type": "compound", "difficulty": 2,
     "met": 5.5, "photo": "https://via.placeholder.com/400x300?text=DB-Row",
     "instructions": ["Опора на скамью", "Тяни гантель к поясу", "Полная амплитуда"],
     "tips": ["Не крути корпус"], "mistakes": ["Слишком широкое отведение локтя"]},
    {"code": "seated_cable_row", "name_ru": "Тяга нижнего блока", "name_en": "Seated Cable Row",
     "muscle": "back", "equipment": "seated_row", "eq_cat": "stationary", "type": "compound", "difficulty": 1,
     "met": 5.0, "photo": "https://via.placeholder.com/400x300?text=Cable-Row",
     "instructions": ["Сядь, колени чуть согнуты", "Тяни к поясу", "Своди лопатки"],
     "tips": ["Не тяни спиной"], "mistakes": ["Округление поясницы"]},
    {"code": "lat_pulldown", "name_ru": "Тяга верхнего блока", "name_en": "Lat Pulldown",
     "muscle": "back", "equipment": "lat_pulldown", "eq_cat": "stationary", "type": "compound", "difficulty": 1,
     "met": 5.0, "photo": "https://via.placeholder.com/400x300?text=Lat-Pulldown",
     "instructions": ["Хват чуть шире плеч", "Тяни к верхней груди", "Медленно вверх"],
     "tips": ["Локти вниз и чуть назад"], "mistakes": ["Отклон назад", "Рывки"]},
    {"code": "deadlift", "name_ru": "Становая тяга", "name_en": "Deadlift",
     "muscle": "back", "equipment": "barbell", "eq_cat": "portable", "type": "compound", "difficulty": 5,
     "met": 6.0, "photo": "https://via.placeholder.com/400x300?text=Deadlift",
     "instructions": ["Ноги на ширине плеч", "Гриф над шнурками", "Спина прямая, тяни вдоль тела"],
     "tips": ["Лопатки назад-вниз"], "mistakes": ["Круглая спина", "Гриф далеко от тела"]},
]
